artifacts_root: artifacts
data_ingestion:
  local_data_file: artifacts/data_ingestion
  root_dir: artifacts/data_ingestion
  ticker: TSLA
data_transformation:
  data_path: artifacts/data_ingestion/data.csv
  root_dir: artifacts/data_transformation
  scaled_data_file: artifacts/data_transformation/scaled_data.npy
  scaler_file_path: artifacts/data_transformation/scaler.joblib
data_validation:
  STATUS_FILE: artifacts/data_validation/status.txt
  local_data_file: artifacts/data_ingestion/data.csv
  root_dir: artifacts/data_validation
full_model_trainer:
  X_stacked_data_path: artifacts/data_transformation/X_stacked.npy
  final_model_name: artifacts/full_model_trainer/model.h5
  partial_model_name: artifacts/partial_model_trainer/partial_model.h5
  root_dir: artifacts/full_model_trainer
  y_stacked_data_path: artifacts/data_transformation/y_stacked.npy
model_evaluation:
  X_test_data_path: artifacts/data_transformation/X_test.npy
  metric_file_name: artifacts/model_evaluation/metrics.json
  model_path: artifacts/partial_model_trainer/partial_model.h5
  root_dir: artifacts/model_evaluation
  scaler_file_path: artifacts/data_transformation/scaler.joblib
  y_test_data_path: artifacts/data_transformation/y_test.npy
partial_model_trainer:
  X_train_data_path: artifacts/data_transformation/X_train.npy
  partial_model_name: artifacts/partial_model_trainer/partial_model.h5
  root_dir: artifacts/partial_model_trainer
  y_train_data_path: artifacts/data_transformation/y_train.npy
